/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym;



import com.mysql.cj.protocol.Resultset;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import java.sql.ResultSet;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import java.util.Vector;



/**
 *
 * @author prabash
 */
public class trainer_details extends javax.swing.JFrame {

    /**
     * Creates new form Addmembers
     */
    public trainer_details() {
        initComponents();
        Connect();
        
        table_log();
    
    }
        Connection con;
        PreparedStatement pst;
        DefaultTableModel df;
        
    
    public void Connect(){
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); // load mysql to the jdbc driver
            //Establish connection to the database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gymmanagementsystem","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(trainer_details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(trainer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void table_log(){
        try {
            pst = con.prepareStatement("select * from members");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            int c;
            c = rd.getColumnCount();

            
            ArrayList<String> columnames = new ArrayList<>();
            
            for (int i = 1; i <= c; i++) {
                columnames.add(rd.getColumnName(i));
            }
            
            df = (DefaultTableModel)jtable1.getModel();
            df.setColumnIdentifiers(columnames.toArray()); 
            
            ArrayList<Object[]> data = new ArrayList<>();
            
            while(rs.next()){
                Object[] row = new Object[c];
                for(int i=0;i<c; i++){
                    row[i] = rs.getObject(i+1);
                }
                
                data.add(row);
            }
            
            for(Object[] row : data){
                df.addRow(row);
            }
           
            
            
        } catch (SQLException ex) {
            Logger.getLogger(trainer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    public void table_load(){
       
        try {
            pst = con.prepareStatement("select * from members");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rd = rs.getMetaData();
            int c;
            c = rd.getColumnCount();
            
           while(rs.next()){
               
                Vector<Object> cnames = new Vector<>();
            
            for(int i=1; i<= c; i++){
                
                cnames.add(rs.getString("id"));
                cnames.add(rs.getString("name"));
                cnames.add(rs.getString("age"));
                cnames.add(rs.getString("address"));
                cnames.add(rs.getString("phonenum"));
                
            }
            
            df.addRow(cnames);
                         
           }
            
                       
        } catch (SQLException ex) {
            Logger.getLogger(trainer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        mob_txt = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        address_btn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        jupdate_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        del_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("addmem"); // NOI18N

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        jLabel3.setText("Mobile number");

        mob_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mob_txtActionPerformed(evt);
            }
        });

        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_btn.setText("ADD");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        jLabel5.setText("Address");

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MemberID", "Name", "Age", "Phone number"
            }
        ));
        jtable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable1);

        jupdate_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jupdate_btn.setText("Update");
        jupdate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdate_btnActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Trainers Details");
        jLabel4.setOpaque(true);

        del_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        del_btn.setText("Delete");
        del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(68, 68, 68)
                            .addComponent(jupdate_btn)
                            .addGap(67, 67, 67)
                            .addComponent(del_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(128, 128, 128)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(agetxt)
                                .addComponent(nametxt)
                                .addComponent(address_btn)
                                .addComponent(mob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mob_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jupdate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(del_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        
        String name = nametxt.getText();
        String age = agetxt.getText();
        String address = address_btn.getText();
        String phonenum = mob_txt.getText();
       
        
        try {
            pst = con.prepareStatement("insert into members(name,age,address,phonenum)values(?,?,?,?)");
            
            pst.setString(1, name);
            pst.setString(2, age);
            pst.setString(3, address);
            pst.setString(4, phonenum);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Trainer Added!");
            
            nametxt.setText("");
            agetxt.setText("");
            address_btn.setText("");
            mob_txt.setText("");
            
            
            
            nametxt.requestFocus();
            df.setRowCount(0);
            table_load();
            
        } catch (SQLException ex) {
            Logger.getLogger(trainer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_add_btnActionPerformed

    private void mob_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mob_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mob_txtActionPerformed

    private void jtable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable1MouseClicked
        // TODO add your handling code here:
        df = (DefaultTableModel)jtable1.getModel();
        int selected = jtable1.getSelectedRow();
        
        int id = Integer.parseInt( df.getValueAt(selected, 0).toString());
        nametxt.setText(df.getValueAt(selected, 1).toString());
        agetxt.setText(df.getValueAt(selected, 2).toString());
        address_btn.setText(df.getValueAt(selected, 3).toString());
        mob_txt.setText(df.getValueAt(selected, 4).toString());
        
        
        
        
        
    }//GEN-LAST:event_jtable1MouseClicked

    private void jupdate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdate_btnActionPerformed
        // TODO add your handling code here:
        
        df = (DefaultTableModel)jtable1.getModel();
        int selected = jtable1.getSelectedRow();
        
        int id = Integer.parseInt( df.getValueAt(selected, 0).toString());
         String name = nametxt.getText();
        String age = agetxt.getText();
        String address = address_btn.getText();
        String phonenum = mob_txt.getText();
       
        
        try {
            pst = con.prepareStatement("update members set name = ?,age=?,address=?,phonenum=? where id=?");
            
            pst.setString(1, name);
            pst.setString(2, age);
            pst.setString(3, address);
            pst.setString(4, phonenum);
            pst.setInt(5, id);
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Member Updated!");
            
            nametxt.setText("");
            agetxt.setText("");
            address_btn.setText("");
            mob_txt.setText("");
            
            
            add_btn.setVisible(true);
            
            
            
            
            
            nametxt.requestFocus();
            df.setRowCount(0);
            table_load();
            
        } catch (SQLException ex) {
            Logger.getLogger(trainer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jupdate_btnActionPerformed

    private void del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btnActionPerformed
        // TODO add your handling code here:
        
         df = (DefaultTableModel)jtable1.getModel();
        int selected = jtable1.getSelectedRow();
        
        int id = Integer.parseInt( df.getValueAt(selected, 0).toString());
        
       
        
        try {
            pst = con.prepareStatement("delete from members where id=?");
       
            pst.setInt(1, id);
            pst.executeUpdate();
            
           
            
            JOptionPane.showMessageDialog(this, "Member deleted!");
            
            nametxt.setText("");
            agetxt.setText("");
            address_btn.setText("");
            mob_txt.setText("");
            
            
            add_btn.setVisible(true);
           
            nametxt.requestFocus();
            df.setRowCount(0);
            table_load();
            
        } catch (SQLException ex) {
            Logger.getLogger(trainer_details.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_del_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trainer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trainer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trainer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trainer_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trainer_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField address_btn;
    private javax.swing.JTextField agetxt;
    private javax.swing.JButton del_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable1;
    private javax.swing.JButton jupdate_btn;
    private javax.swing.JTextField mob_txt;
    private javax.swing.JTextField nametxt;
    // End of variables declaration//GEN-END:variables
}
